In [4]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

from collections import Counter
from sklearn.datasets import make_classification

In [14]:
iris_df = pd.read_csv('./iris-data.csv')
iris_df

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,2.3,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [8]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   150 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   145 non-null    float64
 4   class            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [19]:
iris_df.describe()

       sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
count       150.000000      150.000000       150.000000      145.000000
mean          5.644627        3.054667         3.758667        1.236552
std           1.312781        0.433123         1.764420        0.755058
min           0.055000        2.000000         1.000000        0.100000
25%           5.100000        2.800000         1.600000        0.400000
50%           5.700000        3.000000         4.350000        1.300000
75%           6.400000        3.300000         5.100000        1.800000
max           7.900000        4.400000         6.900000        2.500000

In [20]:
iris_df['class'].unique()

array(['Iris-setosa', 'Iris-setossa', 'Iris-versicolor', 'versicolor',
       'Iris-virginica'], dtype=object)

In [21]:
iris_df['class'].replace('Iris-setossa','Iris-setosa',inplace=True)
iris_df['class'].replace('versicolor','Iris-versicolor',inplace=True)
iris_df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [22]:
iris_df.isnull().sum()

sepal_length_cm    0
sepal_width_cm     0
petal_length_cm    0
petal_width_cm     5
class              0
dtype: int64

In [23]:
iris_df['petal_width_cm'].median()

1.3

In [25]:
iris_input = iris_df.copy()
iris_input

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,2.3,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [26]:
iris_input['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [29]:
iris_input['petal_width_cm'] = iris_input['petal_width_cm'].fillna(iris_input['petal_width_cm'].mean())

In [30]:
iris_input.isnull().sum()

sepal_length_cm    0
sepal_width_cm     0
petal_length_cm    0
petal_width_cm     0
class              0
dtype: int64

In [36]:
iris_one_hot_encoding = pd.get_dummies(iris_input,columns = ['class'], drop_first=True)
iris_one_hot_encoding

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,class_Iris-versicolor,class_Iris-virginica
0,5.1,3.5,1.4,0.2,0,0
1,4.9,3.0,1.4,0.2,0,0
2,4.7,3.2,1.3,0.2,0,0
3,4.6,3.1,1.5,0.2,0,0
4,5.0,3.6,1.4,0.2,0,0
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,1
146,6.3,2.5,5.0,2.3,0,1
147,6.5,3.0,5.2,2.0,0,1
148,6.2,3.4,5.4,2.3,0,1
149,5.9,3.0,5.1,1.8,0,1

In [37]:
sample_data = iris_one_hot_encoding[['sepal_length_cm', 'sepal_width_cm','petal_length_cm','petal_width_cm']]
sample_data.describe()

       sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
count       150.000000      150.000000       150.000000      150.000000
mean          5.644627        3.054667         3.758667        1.236552
std           1.312781        0.433123         1.764420        0.742281
min           0.055000        2.000000         1.000000        0.100000
25%           5.100000        2.800000         1.600000        0.400000
50%           5.700000        3.000000         4.350000        1.300000
75%           6.400000        3.300000         5.100000        1.800000
max           7.900000        4.400000         6.900000        2.500000

In [38]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(sample_data)
scaled_data

array([[-4.16254538e-01,  1.03163593e+00, -1.34127240e+00,
        -1.40111854e+00],
       [-5.69113207e-01, -1.26637944e-01, -1.34127240e+00,
        -1.40111854e+00],
       [-7.21971877e-01,  3.36671607e-01, -1.39813811e+00,
        -1.40111854e+00],
       [-7.98401212e-01,  1.05016832e-01, -1.28440670e+00,
        -1.40111854e+00],
       [-4.92683873e-01,  1.26329071e+00, -1.34127240e+00,
        -1.40111854e+00],
       [-1.86966534e-01,  1.95825503e+00, -1.17067529e+00,
        -1.13077631e+00],
       [-7.98401212e-01,  7.99981158e-01, -1.34127240e+00,
        -1.26594742e+00],
       [-4.92683873e-01,  7.99981158e-01, -1.28440670e+00,
         6.00280343e-16],
       [-9.51259881e-01, -3.58292719e-01, -1.34127240e+00,
         6.00280343e-16],
       [-5.69113207e-01,  1.05016832e-01, -1.28440670e+00,
         6.00280343e-16],
       [-1.86966534e-01,  1.49494548e+00, -1.28440670e+00,
         6.00280343e-16],
       [-6.45542542e-01,  7.99981158e-01, -1.22754100e+00,
         6.00280343e-16],
       [-6.45542542e-01, -1.26637944e-01, -1.34127240e+00,
        -1.53628966e+00],
       [ 4.23214703e-02, -1.26637944e-01, -1.51186952e+00,
        -1.53628966e+00],
       [ 1.18750805e-01,  2.18990981e+00, -1.45500381e+00,
        -1.40111854e+00],
       [ 4.23214703e-02,  3.11652891e+00, -1.28440670e+00,
        -1.13077631e+00],
       [-1.86966534e-01,  1.95825503e+00, -1.39813811e+00,
        -1.13077631e+00],
       [-4.16254538e-01,  1.03163593e+00, -1.34127240e+00,
        -1.26594742e+00],
       [ 4.23214703e-02,  1.72660026e+00, -1.17067529e+00,
        -1.26594742e+00],
       [-4.16254538e-01,  1.72660026e+00, -1.28440670e+00,
        -1.26594742e+00],
       [-1.86966534e-01,  7.99981158e-01, -1.17067529e+00,
        -1.40111854e+00],
       [-4.16254538e-01,  1.49494548e+00, -1.28440670e+00,
        -1.13077631e+00],
       [-7.98401212e-01,  1.26329071e+00, -1.56873522e+00,
        -1.40111854e+00],
       [-4.16254538e-01,  5.68326382e-01, -1.17067529e+00,
        -9.95605190e-01],
       [-6.45542542e-01,  7.99981158e-01, -1.05694388e+00,
        -1.40111854e+00],
       [-4.92683873e-01, -1.26637944e-01, -1.22754100e+00,
        -1.40111854e+00],
       [-4.92683873e-01,  7.99981158e-01, -1.22754100e+00,
        -1.13077631e+00],
       [-3.39825203e-01,  1.03163593e+00, -1.28440670e+00,
        -1.40111854e+00],
       [-3.39825203e-01,  7.99981158e-01, -1.34127240e+00,
        -1.40111854e+00],
       [-7.21971877e-01,  3.36671607e-01, -1.22754100e+00,
        -1.40111854e+00],
       [-6.45542542e-01,  1.05016832e-01, -1.22754100e+00,
        -1.40111854e+00],
       [-1.86966534e-01,  7.99981158e-01, -1.28440670e+00,
        -1.13077631e+00],
       [-3.39825203e-01,  2.42156459e+00, -1.28440670e+00,
        -1.53628966e+00],
       [-1.10537199e-01,  2.65321936e+00, -1.34127240e+00,
        -1.40111854e+00],
       [-5.69113207e-01,  1.05016832e-01, -1.28440670e+00,
        -1.53628966e+00],
       [-4.92683873e-01,  3.36671607e-01, -1.45500381e+00,
        -1.40111854e+00],
       [-1.10537199e-01,  1.03163593e+00, -1.39813811e+00,
        -1.40111854e+00],
       [-5.69113207e-01,  1.05016832e-01, -1.28440670e+00,
        -1.53628966e+00],
       [-9.51259881e-01, -1.26637944e-01, -1.39813811e+00,
        -1.40111854e+00],
       [-4.16254538e-01,  7.99981158e-01, -1.28440670e+00,
        -1.40111854e+00],
       [-4.92683873e-01,  1.03163593e+00, -1.39813811e+00,
        -1.26594742e+00],
       [-8.74830546e-01, -1.74822137e+00, -1.39813811e+00,
        -1.26594742e+00],
       [-9.51259881e-01,  3.36671607e-01, -1.39813811e+00,
        -1.40111854e+00],
       [-4.92683873e-01,  1.03163593e+00, -1.22754100e+00,
        -8.60434073e-01],
       [-4.16254538e-01,  1.72660026e+00, -1.05694388e+00,
        -1.13077631e+00],
       [-6.45542542e-01, -1.26637944e-01, -1.34127240e+00,
        -1.26594742e+00],
       [-4.16254538e-01,  1.72660026e+00, -1.22754100e+00,
        -1.40111854e+00],
       [-7.98401212e-01,  3.36671607e-01, -1.34127240e+00,
        -1.40111854e+00],
       [-2.63395869e-01,  1.49494548e+00, -1.28440670e+00,
        -1.40111854e+00],
       [-4.92683873e-01,  5.68326382e-01, -1.34127240e+00,
        -1.40111854e+00],
       [ 1.03590282e+00,  3.36671607e-01,  5.35295827e-01,
         2.20934859e-01],
       [ 5.77326813e-01,  3.36671607e-01,  4.21564419e-01,
         3.56105976e-01],
       [ 9.59473487e-01,  1.05016832e-01,  6.49027235e-01,
         3.56105976e-01],
       [-1.10537199e-01, -1.74822137e+00,  1.37235899e-01,
         8.57637429e-02],
       [ 6.53756148e-01, -5.89947495e-01,  4.78430123e-01,
         3.56105976e-01],
       [ 4.23214703e-02, -5.89947495e-01,  4.21564419e-01,
         8.57637429e-02],
       [ 5.00897479e-01,  5.68326382e-01,  5.35295827e-01,
         4.91277093e-01],
       [-5.69113207e-01, -1.51656660e+00, -2.60824029e-01,
        -3.19749607e-01],
       [ 7.30185483e-01, -3.58292719e-01,  4.78430123e-01,
         8.57637429e-02],
       [-3.39825203e-01, -8.21602270e-01,  8.03701950e-02,
         2.20934859e-01],
       [-4.92683873e-01, -2.44318570e+00, -1.47092621e-01,
        -3.19749607e-01],
       [ 1.95180140e-01, -1.26637944e-01,  2.50967307e-01,
         3.56105976e-01],
       [ 2.71609474e-01, -1.97987615e+00,  1.37235899e-01,
        -3.19749607e-01],
       [ 3.48038809e-01, -3.58292719e-01,  5.35295827e-01,
         2.20934859e-01],
       [-3.41078644e-02, -3.58292719e-01, -9.02269170e-02,
         8.57637429e-02],
       [ 8.06614817e-01,  1.05016832e-01,  3.64698715e-01,
         2.20934859e-01],
       [-3.41078644e-02, -1.26637944e-01,  4.21564419e-01,
         3.56105976e-01],
       [ 1.18750805e-01, -8.21602270e-01,  1.94101603e-01,
        -3.19749607e-01],
       [ 4.24468144e-01, -1.97987615e+00,  4.21564419e-01,
         3.56105976e-01],
       [-3.41078644e-02, -1.28491182e+00,  8.03701950e-02,
        -1.84578490e-01],
       [ 1.95180140e-01,  3.36671607e-01,  5.92161531e-01,
         7.61619326e-01],
       [ 3.48038809e-01, -5.89947495e-01,  1.37235899e-01,
         8.57637429e-02],
       [ 5.00897479e-01, -1.28491182e+00,  6.49027235e-01,
         3.56105976e-01],
       [ 3.48038809e-01, -5.89947495e-01,  5.35295827e-01,
        -4.94073736e-02],
       [ 5.77326813e-01, -3.58292719e-01,  3.07833011e-01,
         8.57637429e-02],
       [ 7.30185483e-01, -1.26637944e-01,  3.64698715e-01,
         2.20934859e-01],
       [ 8.83044152e-01, -5.89947495e-01,  5.92161531e-01,
         2.20934859e-01],
       [-4.26294295e+00, -1.26637944e-01,  7.05892939e-01,
         6.26448209e-01],
       [-4.26829301e+00, -3.58292719e-01,  4.21564419e-01,
         3.56105976e-01],
       [-4.27058589e+00, -1.05325705e+00, -1.47092621e-01,
        -3.19749607e-01],
       [-4.27211447e+00, -1.51656660e+00,  2.35044910e-02,
        -1.84578490e-01],
       [-4.27211447e+00, -1.51656660e+00, -3.33612130e-02,
        -3.19749607e-01],
       [ 1.18750805e-01, -8.21602270e-01,  8.03701950e-02,
        -4.94073736e-02],
       [ 2.71609474e-01, -5.89947495e-01,  7.62758643e-01,
         4.91277093e-01],
       [-1.86966534e-01, -1.26637944e-01,  4.21564419e-01,
         3.56105976e-01],
       [ 2.71609474e-01,  7.99981158e-01,  4.21564419e-01,
         4.91277093e-01],
       [ 8.06614817e-01,  1.05016832e-01,  5.35295827e-01,
         3.56105976e-01],
       [ 5.00897479e-01, -1.74822137e+00,  3.64698715e-01,
         8.57637429e-02],
       [-3.41078644e-02, -1.26637944e-01,  1.94101603e-01,
         8.57637429e-02],
       [-1.10537199e-01, -1.28491182e+00,  1.37235899e-01,
         8.57637429e-02],
       [-1.10537199e-01, -1.05325705e+00,  3.64698715e-01,
        -4.94073736e-02],
       [ 3.48038809e-01, -1.26637944e-01,  4.78430123e-01,
         2.20934859e-01],
       [ 1.18750805e-01, -1.05325705e+00,  1.37235899e-01,
        -4.94073736e-02],
       [-4.92683873e-01, -1.74822137e+00, -2.60824029e-01,
        -3.19749607e-01],
       [-3.41078644e-02, -8.21602270e-01,  2.50967307e-01,
         8.57637429e-02],
       [ 4.23214703e-02, -1.26637944e-01,  2.50967307e-01,
        -4.94073736e-02],
       [ 4.23214703e-02, -3.58292719e-01,  2.50967307e-01,
         8.57637429e-02],
       [ 4.24468144e-01, -3.58292719e-01,  3.07833011e-01,
         8.57637429e-02],
       [-4.16254538e-01, -1.28491182e+00, -4.31421141e-01,
        -1.84578490e-01],
       [ 4.23214703e-02, -5.89947495e-01,  1.94101603e-01,
         8.57637429e-02],
       [ 5.00897479e-01,  5.68326382e-01,  1.27454998e+00,
         1.70781714e+00],
       [ 1.18750805e-01, -8.21602270e-01,  7.62758643e-01,
         8.96790442e-01],
       [ 1.11233216e+00, -1.26637944e-01,  1.21768427e+00,
         1.16713268e+00],
       [ 5.00897479e-01, -3.58292719e-01,  1.04708716e+00,
         7.61619326e-01],
       [ 6.53756148e-01, -1.26637944e-01,  1.16081857e+00,
         1.30230379e+00],
       [ 1.49447883e+00, -1.26637944e-01,  1.61574420e+00,
         1.16713268e+00],
       [-5.69113207e-01, -1.28491182e+00,  4.21564419e-01,
         6.26448209e-01],
       [ 1.26519083e+00, -3.58292719e-01,  1.44514709e+00,
         7.61619326e-01],
       [ 8.06614817e-01, -1.28491182e+00,  1.16081857e+00,
         7.61619326e-01],
       [ 1.18876149e+00,  1.26329071e+00,  1.33141568e+00,
         1.70781714e+00],
       [ 6.53756148e-01,  3.36671607e-01,  7.62758643e-01,
         1.03196156e+00],
       [ 5.77326813e-01, -8.21602270e-01,  8.76490051e-01,
         8.96790442e-01],
       [ 8.83044152e-01, -1.26637944e-01,  9.90221459e-01,
         1.16713268e+00],
       [ 4.23214703e-02, -1.28491182e+00,  7.05892939e-01,
         1.03196156e+00],
       [ 1.18750805e-01, -5.89947495e-01,  7.62758643e-01,
         1.57264602e+00],
       [ 5.77326813e-01,  3.36671607e-01,  8.76490051e-01,
         1.43747491e+00],
       [ 6.53756148e-01, -1.26637944e-01,  9.90221459e-01,
         7.61619326e-01],
       [ 1.57090816e+00,  1.72660026e+00,  1.67260991e+00,
         1.30230379e+00],
       [ 1.57090816e+00, -1.05325705e+00,  1.78634131e+00,
         1.43747491e+00],
       [ 2.71609474e-01, -1.97987615e+00,  7.05892939e-01,
         3.56105976e-01],
       [ 9.59473487e-01,  3.36671607e-01,  1.10395287e+00,
         1.43747491e+00],
       [-3.41078644e-02, -5.89947495e-01,  6.49027235e-01,
         1.03196156e+00],
       [-3.41078644e-02, -5.89947495e-01,  1.67260991e+00,
         1.03196156e+00],
       [ 5.00897479e-01, -8.21602270e-01,  6.49027235e-01,
         7.61619326e-01],
       [ 8.06614817e-01,  5.68326382e-01,  1.10395287e+00,
         1.16713268e+00],
       [ 1.18876149e+00,  3.36671607e-01,  1.27454998e+00,
         7.61619326e-01],
       [ 4.24468144e-01, -5.89947495e-01,  5.92161531e-01,
         7.61619326e-01],
       [ 3.48038809e-01, -1.26637944e-01,  6.49027235e-01,
         7.61619326e-01],
       [ 5.77326813e-01, -5.89947495e-01,  1.04708716e+00,
         1.16713268e+00],
       [ 1.18876149e+00, -1.26637944e-01,  1.16081857e+00,
         4.91277093e-01],
       [ 1.34162016e+00, -5.89947495e-01,  1.33141568e+00,
         8.96790442e-01],
       [ 1.72376683e+00,  1.72660026e+00,  1.50201279e+00,
         1.03196156e+00],
       [ 5.77326813e-01, -5.89947495e-01,  1.04708716e+00,
         1.30230379e+00],
       [ 5.00897479e-01, -5.89947495e-01,  7.62758643e-01,
         3.56105976e-01],
       [ 3.48038809e-01, -1.05325705e+00,  1.04708716e+00,
         2.20934859e-01],
       [ 1.57090816e+00, -1.26637944e-01,  1.33141568e+00,
         1.43747491e+00],
       [ 5.00897479e-01,  7.99981158e-01,  1.04708716e+00,
         1.57264602e+00],
       [ 5.77326813e-01,  1.05016832e-01,  9.90221459e-01,
         7.61619326e-01],
       [ 2.71609474e-01, -1.26637944e-01,  5.92161531e-01,
         7.61619326e-01],
       [ 9.59473487e-01,  1.05016832e-01,  9.33355755e-01,
         1.16713268e+00],
       [ 8.06614817e-01,  1.05016832e-01,  1.04708716e+00,
         1.57264602e+00],
       [ 9.59473487e-01,  1.05016832e-01,  7.62758643e-01,
         1.43747491e+00],
       [ 1.18750805e-01, -8.21602270e-01,  7.62758643e-01,
         8.96790442e-01],
       [ 8.83044152e-01,  3.36671607e-01,  1.21768427e+00,
         1.43747491e+00],
       [ 8.06614817e-01,  5.68326382e-01,  1.10395287e+00,
         1.70781714e+00],
       [ 8.06614817e-01, -1.26637944e-01,  8.19624347e-01,
         1.43747491e+00],
       [ 5.00897479e-01, -1.28491182e+00,  7.05892939e-01,
         1.43747491e+00],
       [ 6.53756148e-01, -1.26637944e-01,  8.19624347e-01,
         1.03196156e+00],
       [ 4.24468144e-01,  7.99981158e-01,  9.33355755e-01,
         1.43747491e+00],
       [ 1.95180140e-01, -1.26637944e-01,  7.62758643e-01,
         7.61619326e-01]])

In [42]:
scaled_df = pd.DataFrame(scaled_data, columns=['sepal_length_cm', 'sepal_width_cm','petal_length_cm','petal_width_cm'])
scaled_df

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
0          -0.416255        1.031636        -1.341272       -1.401119
1          -0.569113       -0.126638        -1.341272       -1.401119
2          -0.721972        0.336672        -1.398138       -1.401119
3          -0.798401        0.105017        -1.284407       -1.401119
4          -0.492684        1.263291        -1.341272       -1.401119
..               ...             ...              ...             ...
145         0.806615       -0.126638         0.819624        1.437475
146         0.500897       -1.284912         0.705893        1.437475
147         0.653756       -0.126638         0.819624        1.031962
148         0.424468        0.799981         0.933356        1.437475
149         0.195180       -0.126638         0.762759        0.761619

[150 rows x 4 columns]